inherit_from: ~/.config/rubocop/config.yml

AllCops:
  Exclude:
    - 'bin/*'

Layout/LineLength:
  Exclude:
    - 'spec/**/*.rb'

# setting to 6 to match RubyMine autoformat
Layout/FirstArrayElementIndentation:
  IndentationWidth: 6

# rspec blocks are huge by design
Metrics/BlockLength:
  Exclude:
    - 'tests/spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'tests/spec/**/*.rb'
