inherit_from: ~/.config/rubocop/config.yml

AllCops:
  Exclude:
    - 'bin/*'

Layout/LineLength:
  Exclude:
    - 'spec/**/*.rb'

# setting to 6 to match RubyMine autoformat
Layout/FirstArrayElementIndentation:
  IndentationWidth: 6
